import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const EZYSHIELD_OPPORTUNITY_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.SELECT,
    name: 'salesStage',
    label: 'Sales Stage',
    description: 'EzyShield specific sales process stage',
    icon: 'IconTargetArrow',
    isActive: true,
    isNullable: false,
    isUnique: false,
    options: [
      {
        color: 'gray',
        label: 'New Lead',
        position: 0,
        value: 'NEW_LEAD',
      },
      {
        color: 'blue',
        label: 'Research & Qualification',
        position: 1,
        value: 'RESEARCH_QUALIFICATION',
      },
      {
        color: 'purple',
        label: 'Technical Assessment',
        position: 2,
        value: 'TECHNICAL_ASSESSMENT',
      },
      {
        color: 'turquoise',
        label: 'API Integration Discussion',
        position: 3,
        value: 'API_INTEGRATION',
      },
      {
        color: 'sky',
        label: 'Demo Scheduled',
        position: 4,
        value: 'DEMO_SCHEDULED',
      },
      {
        color: 'green',
        label: 'Proposal Sent',
        position: 5,
        value: 'PROPOSAL_SENT',
      },
      {
        color: 'yellow',
        label: 'Contract Review',
        position: 6,
        value: 'CONTRACT_REVIEW',
      },
      {
        color: 'emerald',
        label: 'Closed Won',
        position: 7,
        value: 'CLOSED_WON',
      },
      {
        color: 'red',
        label: 'Closed Lost',
        position: 8,
        value: 'CLOSED_LOST',
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'integrationType',
    label: 'Integration Type',
    description: 'Type of integration being discussed',
    icon: 'IconApi',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'blue',
        label: 'API',
        position: 0,
        value: 'API',
      },
      {
        color: 'green',
        label: 'ABA File',
        position: 1,
        value: 'ABA_FILE',
      },
      {
        color: 'purple',
        label: 'Both',
        position: 2,
        value: 'BOTH',
      },
    ],
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'estimatedImplementationMonths',
    label: 'Est. Implementation (Months)',
    description: 'Estimated implementation time in months',
    icon: 'IconCalendar',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'leadSource',
    label: 'Lead Source',
    description: 'Source of the lead',
    icon: 'IconSource',
    isActive: true,
    isNullable: false,
    isUnique: false,
    options: [
      {
        color: 'blue',
        label: 'Outbound',
        position: 0,
        value: 'OUTBOUND',
      },
      {
        color: 'green',
        label: 'Inbound',
        position: 1,
        value: 'INBOUND',
      },
      {
        color: 'purple',
        label: 'Referral',
        position: 2,
        value: 'REFERRAL',
      },
      {
        color: 'yellow',
        label: 'Partnership',
        position: 3,
        value: 'PARTNERSHIP',
      },
      {
        color: 'gray',
        label: 'Other',
        position: 4,
        value: 'OTHER',
      },
    ],
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'fitScore',
    label: 'Fit Score',
    description: 'AI-calculated lead fit score (1-10)',
    icon: 'IconTarget',
    isActive: true,
    isNullable: true,
    isUnique: false,
    settings: {
      min: 1,
      max: 10,
    },
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'rejectionReason',
    label: 'Rejection Reason',
    description: 'Reason for opportunity loss',
    icon: 'IconX',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'decisionMakerTitle',
    label: 'Decision Maker Title',
    description: 'Title of primary decision maker',
    icon: 'IconUser',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'blue',
        label: 'CEO',
        position: 0,
        value: 'CEO',
      },
      {
        color: 'purple',
        label: 'CTO',
        position: 1,
        value: 'CTO',
      },
      {
        color: 'green',
        label: 'CFO',
        position: 2,
        value: 'CFO',
      },
      {
        color: 'yellow',
        label: 'VP Engineering',
        position: 3,
        value: 'VP_ENGINEERING',
      },
      {
        color: 'turquoise',
        label: 'VP Finance',
        position: 4,
        value: 'VP_FINANCE',
      },
      {
        color: 'sky',
        label: 'Head of Payments',
        position: 5,
        value: 'HEAD_OF_PAYMENTS',
      },
      {
        color: 'gray',
        label: 'Other',
        position: 6,
        value: 'OTHER',
      },
    ],
  },
];
