import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const EZYSHIELD_COMPANY_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.SELECT,
    name: 'companyType',
    label: 'Company Type',
    description: 'Target market segment for EzyShield solution',
    icon: 'IconBuildingSkyscraper',
    isActive: true,
    isNullable: false,
    isUnique: false,
    options: [
      {
        color: 'blue',
        label: 'Payment Company',
        position: 0,
        value: 'PAYMENT_COMPANY',
      },
      {
        color: 'purple',
        label: 'Labor Hire',
        position: 1,
        value: 'LABOR_HIRE',
      },
      {
        color: 'green',
        label: 'SMB',
        position: 2,
        value: 'SMB',
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'integrationPreference',
    label: 'Integration Preference',
    description: 'Preferred integration method for EzyShield',
    icon: 'IconApi',
    isActive: true,
    isNullable: false,
    isUnique: false,
    options: [
      {
        color: 'blue',
        label: 'API',
        position: 0,
        value: 'API',
      },
      {
        color: 'green',
        label: 'ABA File',
        position: 1,
        value: 'ABA_FILE',
      },
      {
        color: 'purple',
        label: 'Both',
        position: 2,
        value: 'BOTH',
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'accountingSoftware',
    label: 'Accounting Software',
    description: 'Primary accounting software used by the company',
    icon: 'IconBrandXero',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'blue',
        label: 'Xero',
        position: 0,
        value: 'XERO',
      },
      {
        color: 'yellow',
        label: 'MYOB',
        position: 1,
        value: 'MYOB',
      },
      {
        color: 'green',
        label: 'QuickBooks',
        position: 2,
        value: 'QUICKBOOKS',
      },
      {
        color: 'gray',
        label: 'Other',
        position: 3,
        value: 'OTHER',
      },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'currentPaymentProvider',
    label: 'Current Payment Provider',
    description: 'Current payment processing solution being used',
    icon: 'IconCreditCard',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'estimatedMonthlyTransactionVolume',
    label: 'Monthly Transaction Volume',
    description: 'Estimated number of monthly payment transactions',
    icon: 'IconCurrencyDollar',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'gray',
        label: '< $10K',
        position: 0,
        value: 'UNDER_10K',
      },
      {
        color: 'green',
        label: '$10K - $100K',
        position: 1,
        value: '10K_TO_100K',
      },
      {
        color: 'blue',
        label: '$100K - $1M',
        position: 2,
        value: '100K_TO_1M',
      },
      {
        color: 'purple',
        label: '> $1M',
        position: 3,
        value: 'OVER_1M',
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'technicalComplexity',
    label: 'Technical Complexity',
    description: 'Perceived technical complexity for integration',
    icon: 'IconCode',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'green',
        label: 'Low',
        position: 0,
        value: 'LOW',
      },
      {
        color: 'yellow',
        label: 'Medium',
        position: 1,
        value: 'MEDIUM',
      },
      {
        color: 'red',
        label: 'High',
        position: 2,
        value: 'HIGH',
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'fraudRiskLevel',
    label: 'Fraud Risk Level',
    description: 'Assessed risk level for payment fraud',
    icon: 'IconShield',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'red',
        label: 'High',
        position: 0,
        value: 'HIGH',
      },
      {
        color: 'yellow',
        label: 'Medium',
        position: 1,
        value: 'MEDIUM',
      },
      {
        color: 'green',
        label: 'Low',
        position: 2,
        value: 'LOW',
      },
    ],
  },
];
