import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const OUTREACH_SEQUENCE_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.NUMBER,
    name: 'sequenceStep',
    label: 'Sequence Step',
    description: 'Step number in outreach sequence',
    icon: 'IconHash',
    isActive: true,
    isNullable: false,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'channel',
    label: 'Channel',
    description: 'Communication channel used',
    icon: 'IconMessage',
    isActive: true,
    isNullable: false,
    isUnique: false,
    options: [
      {
        color: 'blue',
        label: 'Email',
        position: 0,
        value: 'EMAIL',
      },
      {
        color: 'blue',
        label: 'LinkedIn',
        position: 1,
        value: 'LINKEDIN',
      },
      {
        color: 'green',
        label: 'Phone',
        position: 2,
        value: 'PHONE',
      },
      {
        color: 'purple',
        label: 'SMS',
        position: 3,
        value: 'SMS',
      },
    ],
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'scheduledDate',
    label: 'Scheduled Date',
    description: 'When outreach is scheduled for',
    icon: 'IconCalendar',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'status',
    label: 'Status',
    description: 'Current status of outreach',
    icon: 'IconStatus',
    isActive: true,
    isNullable: false,
    isUnique: false,
    options: [
      {
        color: 'gray',
        label: 'Scheduled',
        position: 0,
        value: 'SCHEDULED',
      },
      {
        color: 'blue',
        label: 'Sent',
        position: 1,
        value: 'SENT',
      },
      {
        color: 'yellow',
        label: 'Opened',
        position: 2,
        value: 'OPENED',
      },
      {
        color: 'green',
        label: 'Replied',
        position: 3,
        value: 'REPLIED',
      },
      {
        color: 'red',
        label: 'Bounced',
        position: 4,
        value: 'BOUNCED',
      },
      {
        color: 'orange',
        label: 'Skipped',
        position: 5,
        value: 'SKIPPED',
      },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'messageTemplate',
    label: 'Message Template',
    description: 'Template message used',
    icon: 'IconFileText',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'personalizedContent',
    label: 'Personalized Content',
    description: 'Customized content sent',
    icon: 'IconEdit',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'openCount',
    label: 'Open Count',
    description: 'Number of times opened',
    icon: 'IconEye',
    isActive: true,
    isNullable: true,
    isUnique: false,
    defaultValue: 0,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'clickCount',
    label: 'Click Count',
    description: 'Number of times links clicked',
    icon: 'IconCursorClick',
    isActive: true,
    isNullable: true,
    isUnique: false,
    defaultValue: 0,
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'sentDate',
    label: 'Sent Date',
    description: 'When outreach was actually sent',
    icon: 'IconCalendarEvent',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'errorMessage',
    label: 'Error Message',
    description: 'Any error that occurred',
    icon: 'IconAlertTriangle',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
];
