import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const RESEARCH_NOTE_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.SELECT,
    name: 'researchType',
    label: 'Research Type',
    description: 'Source of research',
    icon: 'IconSearch',
    isActive: true,
    isNullable: false,
    isUnique: false,
    options: [
      {
        color: 'blue',
        label: 'LinkedIn',
        position: 0,
        value: 'LINKEDIN',
      },
      {
        color: 'green',
        label: 'Website',
        position: 1,
        value: 'WEBSITE',
      },
      {
        color: 'purple',
        label: 'News',
        position: 2,
        value: 'NEWS',
      },
      {
        color: 'yellow',
        label: 'Social Media',
        position: 3,
        value: 'SOCIAL_MEDIA',
      },
      {
        color: 'gray',
        label: 'Industry Reports',
        position: 4,
        value: 'INDUSTRY_REPORTS',
      },
      {
        color: 'turquoise',
        label: 'Manual',
        position: 5,
        value: 'MANUAL',
      },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'keyFindings',
    label: 'Key Findings',
    description: 'Important insights from research',
    icon: 'IconLightbulb',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'personalizedOutreachAngle',
    label: 'Outreach Angle',
    description: 'Suggested personalized outreach angle',
    icon: 'IconTarget',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'researchDate',
    label: 'Research Date',
    description: 'When research was completed',
    icon: 'IconCalendar',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'aiModelUsed',
    label: 'AI Model',
    description: 'Which AI model generated this research',
    icon: 'IconBrain',
    isActive: true,
    isNullable: true,
    isUnique: false,
    defaultValue: "'Claude 3.5 Sonnet'",
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'citations',
    label: 'Citations',
    description: 'Source URLs/references',
    icon: 'IconBook',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'researchQualityScore',
    label: 'Research Quality',
    description: 'Quality of research data (1-10)',
    icon: 'IconStar',
    isActive: true,
    isNullable: true,
    isUnique: false,
    settings: {
      min: 1,
      max: 10,
    },
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'personName',
    label: 'Person Name',
    description: 'Name of person researched (if applicable)',
    icon: 'IconUser',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'personTitle',
    label: 'Person Title',
    description: 'Title/role of person researched',
    icon: 'IconUserCircle',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
];
